### ISSUE TITLE
What was your plan for this, besides it doesn't seem to be used

### ISSUE THREAD

**Issue by ooade** [Oluwaseunus/anime-characters#8]
https://github.com/Oluwaseunus/anime-characters/blob/4cf0168c6477e00e80955179d3fcfeaca4328478/src/helpers.js#L1

**Comment by Oluwaseunus** [comment]
The first API I tried to use had multiple results that were missing information. Sometimes the type or synopsis or number of episodes would be missing. So I created a function to just output Unknown instead of an empty string, but I realized that that would require wrapping every piece of data used with the function and it just seemed redundant. So I switched to a different API, but forgot to remove the function.

**Comment by ooade** [comment]
Oh, cool.
